---
services:
  k8guard-discover-api:
    build:
      context: ../k8guard-discover/
    networks:
      - k8guardstartfromhere_default
    external_links:
      - k8guardstartfromhere_kafka_1:kafka
      - k8guardstartfromhere_memcached_1:memcached
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - ${HOME}/.kube:/root/.kube
  k8guard-discover-cron:
     build:
        context: ../k8guard-discover/
        dockerfile: Dockerfile-local
     networks:
       - k8guardstartfromhere_default
     env_file:
       - .env
     external_links:
       - k8guardstartfromhere_kafka_1:kafka
       - k8guardstartfromhere_memcached_1:memcached
     volumes:
       - ${HOME}/.kube:/root/.kube
     command:
       - -kmode
version: "2"

networks:
  k8guardstartfromhere_default:
    external: true