apiVersion: v1
kind: ConfigMap
metadata:
  name: k8guard-discover-configmap
data:
  k8guard-namespace: ""
  k8guard-cluster: "tte-test"
  k8guard-approved-image-repos: "REPLACE_ME"
  k8guard-approved-image-size: "800"
  k8guard-ingress-must-contain: ""
  k8guard-ingress-must-not-contain: ""
  k8guard-approved-ingress-suffixes: ""
  k8guard-ignore-namespaces: ""
  k8guard-ignore-pods-prefix: ""
  k8guard-ignore-deployments: ""
  k8guard-ignore-violations: ""
  k8guard-output-pods-to-file: "FALSE"
  k8guard-cache-expiration-seconds: "300"
  k8guard-http-cache-expire: "TRUE"
  k8guard-memcahced-hostname: "k8guard-memcached-service.default.svc.cluster.local"
  k8guard-log-level: "debug"
  k8guard-kafka-brokers: "k8guard-kafka-service.default.svc.cluster.local:9092"
  k8guard-kafka-action-topic: "k8guard-to-action-k8s-lab"
