apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: k8guard-discover-cronjob
spec:
  # At every 3rd minute. for local testing
  schedule: "*/3 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: k8guard-discover-cronjob
              image: local/k8guard-discover
              imagePullPolicy: Never
              args:
                - -kmode
              resources:
                limits:
                  cpu: 500m
                  memory: 700Mi
                requests:
                  cpu: 300m
                  memory: 350Mi
              env:
                - name: K8GUARD_NAMESPACE
                  valueFrom:
                    configMapKeyRef:
                      name: k8guard-discover-configmap
                      key: k8guard-namespace
                - name: K8GUARD_APPROVED_IMAGE_REPOS
                  valueFrom:
                    configMapKeyRef:
                      name: k8guard-discover-configmap
                      key: k8guard-approved-image-repos
                - name: K8GUARD_APPROVED_IMAGE_SIZE
                  valueFrom:
                    configMapKeyRef:
                      name: k8guard-discover-configmap
                      key: k8guard-approved-image-size
                - name: K8GUARD_APPROVED_INGRESS_SUFFIXES
                  valueFrom:
                    configMapKeyRef:
                      name: k8guard-discover-configmap
                      key: k8guard-approved-ingress-suffixes
                - name: K8GUARD_INGRESS_MUST_NOT_CONTAIN
                  valueFrom:
                    configMapKeyRef:
                      name: k8guard-discover-configmap
                      key: k8guard-ingress-must-not-contain
                - name: K8GUARD_IGNORE_NAMESPACES
                  valueFrom:
                    configMapKeyRef:
                      name: k8guard-discover-configmap
                      key: k8guard-ignore-namespaces
                - name: K8GUARD_IGNORE_PODS_PREFIX
                  valueFrom:
                    configMapKeyRef:
                      name: k8guard-discover-configmap
                      key: k8guard-ignore-pods-prefix
                - name: K8GUARD_IGNORE_DEPLOYMENTS
                  valueFrom:
                    configMapKeyRef:
                      name: k8guard-discover-configmap
                      key: k8guard-ignore-deployments
                - name: K8GUARD_OUTPUT_PODS_TO_FILE
                  valueFrom:
                    configMapKeyRef:
                      name: k8guard-discover-configmap
                      key: k8guard-output-pods-to-file
                - name: K8GUARD_CACHE_EXPIRATION_SECONDS
                  valueFrom:
                    configMapKeyRef:
                      name: k8guard-discover-configmap
                      key: k8guard-cache-expiration-seconds
                - name: K8GUARD_MEMCACHED_HOSTNAME
                  valueFrom:
                    configMapKeyRef:
                      name: k8guard-discover-configmap
                      key: k8guard-memcahced-hostname
                - name: K8GUARD_LOG_LEVEL
                  valueFrom:
                    configMapKeyRef:
                      name: k8guard-discover-configmap
                      key: k8guard-log-level
                - name: K8GUARD_KAFKA_BROKERS
                  valueFrom:
                    configMapKeyRef:
                      name: k8guard-discover-configmap
                      key: k8guard-kafka-brokers
                - name: K8GUARD_KAFKA_ACTION_TOPIC
                  valueFrom:
                    configMapKeyRef:
                      name: k8guard-discover-configmap
                      key: k8guard-kafka-action-topic
                - name: K8GUARD_IGNORED_VIOLATIONS
                  valueFrom:
                    configMapKeyRef:
                      name: k8guard-discover-configmap
                      key: k8guard-ignore-violations
