apiVersion: v1
kind: Service
metadata:
  labels:
    name: k8guard-label
  name: k8guard-report-service
spec:
  type: NodePort
  ports:
    # The port that this service should serve on.
    - port: 3001

  # Label keys and values that must match in order to receive traffic for this service.
  selector:
     app: k8guard-report
