apiVersion: v1
kind: Service
metadata:
  labels:
    name: k8guard-cassandra-label
  name: k8guard-cassandra-service
spec:
  ports:
    # The port that this service should serve on.
    - port: 9042

  # Label keys and values that must match in order to receive traffic for this service.
  selector:
     app: k8guard-cassandra
