apiVersion: v1
kind: Service
metadata:
  labels:
    name: k8guard-kafka-label
  name: k8guard-kafka-service
spec:
  ports:
  - port: 2181
    targetPort: 2181
    name: zk
  - port: 9092
    targetPort: 9092
    name: kafka
  # Label keys and values that must match in order to receive traffic for this service.
  selector:
     app: k8guard-kafka
