apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8guard-memcached
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: k8guard-memcached
    spec:
      containers:
      - name: k8guard-memcached
        image: memcached:alpine
